"""Core package for CoT Red Teaming Agent."""

from cot_redteam.core.errors import (
    BudgetExceededError,
    ConfigurationError,
    CotRedTeamError,
    DatasetError,
    PermanentProviderError,
    PluginError,
    ProviderError,
    StorageError,
    TransientProviderError,
)
from cot_redteam.core.serialization import canonical_json, sha256_bytes, sha256_file, sha256_text
from cot_redteam.core.types import (
    AttackAssessment,
    AttackCategory,
    AttackPrompt,
    DatasetSample,
    EvaluationItem,
    EvaluationRun,
    GenerationRequest,
    ItemStatus,
    ModelRef,
    ModelResponse,
    MonitorOutcome,
    MonitorStatus,
    ReasoningSource,
    RunStatus,
    RunSummary,
    TokenUsage,
)

__all__ = [
    "AttackAssessment",
    "AttackCategory",
    "AttackPrompt",
    "BudgetExceededError",
    "ConfigurationError",
    "CotRedTeamError",
    "DatasetError",
    "DatasetSample",
    "EvaluationItem",
    "EvaluationRun",
    "GenerationRequest",
    "ItemStatus",
    "ModelRef",
    "ModelResponse",
    "MonitorOutcome",
    "MonitorStatus",
    "PermanentProviderError",
    "PluginError",
    "ProviderError",
    "ReasoningSource",
    "RunStatus",
    "RunSummary",
    "StorageError",
    "TokenUsage",
    "TransientProviderError",
    "canonical_json",
    "sha256_bytes",
    "sha256_file",
    "sha256_text",
]
